title: Textureless Deformable Surface Reconstruction with Invisible Markers
description: Xinyuan Li, Yu Ji, Yanchen Liu, Xiaochen Hu, Jinwei Ye, Changxi Zheng
date: Aug, 2023
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman # https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  arxiv_url: https://arxiv.org/
  code_url: https://arxiv.org/
  dataset_url: https://arxiv.org/